import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const { data: jobListings, isLoading } = api.job.getJobs.useQuery([], {
    refetchOnReconnect: false,
    refetchOnWindowFocus: false,
  });

  // console.clear();
  console.log(isLoading, jobListings);

  return (
    <>
      <Head>
        <title>Job Listings</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <p>Hello world!</p>
      </main>
    </>
  );
}
